<a href="https://colab.research.google.com/github/NaavyaV/Accenture-1K-contract-review-challenge/blob/dev/Naavya_Vig_GPU_training_experiments_Capstone_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

!pip install -q "transformers>=4.45,<5" torch numpy pandas scikit-learn

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.30.0 requires huggingface-hub<3.0,>=1.16.0, but you have huggingface-hub 0.36.2 which is incompatible.
gradio-client 2.7.2 requires huggingface-hub<3.0,>=1.16.0, but you have huggingface-hub 0.36.2 which is incompatible.
diffusers 0.42.0 requires huggingface-hub<3.0,>=1.32.0, but you have huggingface-hub 0.36.2 which is incompatible.

Import libraries and configure the model

In [2]:

import torch
import numpy as np

from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification
)

MODEL_NAME = "distilbert/distilroberta-base"
NUM_LABELS = 41

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Using device:", DEVICE)

Using device: cuda

Initialize DistilRoBERTa

In [3]:

def initialize_model(
    model_name=MODEL_NAME,
    num_labels=NUM_LABELS
):
    tokenizer = AutoTokenizer.from_pretrained(
        model_name
    )

    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=num_labels,
        problem_type="multi_label_classification"
    )

    model = model.to(DEVICE)

    return model, tokenizer


model, tokenizer = initialize_model()

print("Model initialized successfully!")
print("Number of labels:", model.config.num_labels)

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at distilbert/distilroberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Model initialized successfully!
Number of labels: 41

Create the dataset class

In [4]:

class ContractDataset(Dataset):

    def __init__(self, texts, labels, tokenizer, max_length=256):
        assert len(texts) == len(labels)

        labels = np.asarray(labels, dtype=np.float32)

        assert labels.ndim == 2
        assert labels.shape[1] == NUM_LABELS

        self.encodings = tokenizer(
            texts,
            truncation=True,
            padding="max_length",
            max_length=max_length
        )

        self.labels = torch.tensor(
            labels,
            dtype=torch.float32
        )

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):

        item = {
            key: torch.tensor(values[idx])
            for key, values in self.encodings.items()
        }

        item["labels"] = self.labels[idx]

        return item

Create reusable training function

In [5]:

def train_model(
    model,
    train_loader,
    epochs=3,
    learning_rate=2e-5
):
    optimizer = AdamW(
        model.parameters(),
        lr=learning_rate
    )

    for epoch in range(epochs):

        model.train()
        total_loss = 0

        for batch in train_loader:

            batch = {
                key: value.to(DEVICE)
                for key, value in batch.items()
            }

            optimizer.zero_grad()

            outputs = model(**batch)

            loss = outputs.loss

            loss.backward()

            optimizer.step()

            total_loss += loss.item()

        avg_loss = total_loss / len(train_loader)

        print(
            f"Epoch {epoch + 1}/{epochs} "
            f"- Loss: {avg_loss:.4f}"
        )

    return model

Create reusable prediction function

In [6]:

def predict_clauses(
    text,
    model,
    tokenizer,
    threshold=0.5
):
    model.eval()

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=256
    ).to(DEVICE)

    with torch.no_grad():
        outputs = model(**inputs)

        probabilities = torch.sigmoid(
            outputs.logits
        )

    predictions = (
        probabilities >= threshold
    ).int()

    return {
        "probabilities": probabilities.cpu().numpy()[0],
        "predictions": predictions.cpu().numpy()[0]
    }

Create example training data

In [23]:

import pandas as pd
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
from torch.utils.data import DataLoader

# 1. Load the three files uploaded individually to Colab
train_chunks = pd.read_json("/content/cuad_train_split.jsonl", lines=True)
val_chunks = pd.read_json("/content/cuad_val_split.jsonl", lines=True)
test_chunks = pd.read_json("/content/cuad_test_split.jsonl", lines=True)

# 2. Create a consistent mapping for all 41 categories
categories = sorted({
    category
    for labels in train_chunks["labels"]
    for category in labels
})

assert len(categories) == NUM_LABELS, (
    f"Expected {NUM_LABELS} categories, found {len(categories)}"
)

label_encoder = MultiLabelBinarizer(classes=categories)
label_encoder.fit([[]])

y_train = label_encoder.transform(train_chunks["labels"])
y_val = label_encoder.transform(val_chunks["labels"])
y_test = label_encoder.transform(test_chunks["labels"])

# 3. Build datasets using the ContractDataset class
train_dataset = ContractDataset(
    train_chunks["chunk_text"].fillna("").tolist(),
    y_train,
    tokenizer,
    max_length=512
)

val_dataset = ContractDataset(
    val_chunks["chunk_text"].fillna("").tolist(),
    y_val,
    tokenizer,
    max_length=512
)

test_dataset = ContractDataset(
    test_chunks["chunk_text"].fillna("").tolist(),
    y_test,
    tokenizer,
    max_length=512
)

# 4. Create data loaders
train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False)

# 5. Verify everything loaded
print("Training chunks:", len(train_dataset))
print("Validation chunks:", len(val_dataset))
print("Test chunks:", len(test_dataset))
print("Number of categories:", len(categories))
print("Label vector shape:", y_train.shape)

Training chunks: 11500
Validation chunks: 1998
Test chunks: 1226
Number of categories: 41
Label vector shape: (11500, 41)

In [35]:

import numpy as np
import pandas as pd
import re

splits = {
    "train": (train_chunks, np.asarray(y_train)),
    "validation": (val_chunks, np.asarray(y_val)),
    "test": (test_chunks, np.asarray(y_test))
}

# 1. Contract leakage
ids = {
    name: set(df["contract_id"].astype(str))
    for name, (df, _) in splits.items()
}

print("CONTRACT OVERLAP")
for a, b in [
    ("train", "validation"),
    ("train", "test"),
    ("validation", "test")
]:
    overlap = ids[a] & ids[b]
    print(f"{a} vs {b}: {len(overlap)} shared contracts")
    if overlap:
        print("Examples:", list(overlap)[:5])

# 2. Label distribution
rows = []

for j, category in enumerate(categories):
    row = {"category": category}
    for name, (_, labels) in splits.items():
        row[name + "_positives"] = int(labels[:, j].sum())
    rows.append(row)

freq = pd.DataFrame(rows).sort_values("train_positives")
display(freq)

# 3. Exact duplicate text across splits
def normalized_texts(df):
    return set(
        df["chunk_text"].fillna("")
        .astype(str)
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    ) - {""}

texts = {
    name: normalized_texts(df)
    for name, (df, _) in splits.items()
}

print("\nEXACT TEXT OVERLAP")
for a, b in [
    ("train", "validation"),
    ("train", "test"),
    ("validation", "test")
]:
    print(a, b, len(texts[a] & texts[b]))

# 4. Positive examples for manual inspection
rare = freq.head(8)["category"].tolist()

for category in rare:
    j = list(categories).index(category)
    indices = np.flatnonzero(np.asarray(y_train)[:, j] == 1)

    print("\n" + "=" * 65)
    print(category, "| training positives:", len(indices))

    for i in indices[:2]:
        row = train_chunks.iloc[int(i)]
        print("Contract:", row["contract_id"])
        print("Labels:", row["labels"])
        print("TEXT:")
        print(str(row["chunk_text"])[:1200])
        print("-" * 50)

freq.to_csv("/content/cuad_label_audit.csv", index=False)
print("\nSaved: /content/cuad_label_audit.csv")

CONTRACT OVERLAP
train vs validation: 0 shared contracts
train vs test: 0 shared contracts
validation vs test: 0 shared contracts

,category,train_positives,validation_positives,test_positives
30,Price Restrictions,20,3,1
38,Unlimited/All-You-Can-Eat-License,22,2,1
34,Source Code Escrow,25,7,0
21,Most Favored Nation,25,6,4
22,No-Solicit Of Customers,33,8,8
36,Third Party Beneficiary,33,4,4
25,Non-Disparagement,38,8,7
1,Affiliate License-Licensor,39,3,11
23,No-Solicit Of Employees,56,7,7
17,Joint Ip Ownership,63,6,7
0,Affiliate License-Licensee,64,18,14
7,Competitive Restriction Exception,80,10,10
16,Irrevocable Or Perpetual License,82,23,22
19,Liquidated Damages,84,4,4
40,Warranty Duration,95,19,13
27,Notice Period To Terminate Renewal,96,11,9
37,Uncapped Liability,101,18,13
39,Volume Restriction,110,18,6
8,Covenant Not To Sue,113,17,21
6,Change Of Control,148,29,15
31,Renewal Term,156,20,16
33,Rofr/Rofo/Rofn,160,19,12
24,Non-Compete,166,14,23
26,Non-Transferable License,169,30,34
35,Termination For Convenience,173,27,21
15,Ip Ownership Assignment,176,28,20
14,Insurance,222,31,23
11,Exclusivity,245,45,29
32,Revenue/Profit Sharing,245,31,27
20,Minimum Commitment,277,39,19
29,Post-Termination Services,288,41,21
4,Audit Rights,314,71,27
10,Effective Date,367,47,34
12,Expiration Date,369,57,44
13,Governing Law,378,51,49
2,Agreement Date,386,55,49
3,Anti-Assignment,402,67,50
5,Cap On Liability,407,57,45
9,Document Name,424,57,51
18,License Grant,436,80,69
28,Parties,511,85,61

EXACT TEXT OVERLAP
train validation 1
train test 7
validation test 0

=================================================================
Price Restrictions | training positives: 20
Contract: LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGREEMENT
Labels: ['Price Restrictions']
TEXT:
                       Section   2.4(a)  shall  be  subject  to   adjustment                            annually  on the  first  day  of  each  Product  Year                            beginning in the calendar  year 2000 and on the first                            day of each succeeding Product Year for the remainder                            of the Term and all  renewals  of this  Agreement  in                            proportion   to  the  increase  or  decrease  in  the                            Consumer  Price Index (CPI) as compared to the CPI as                            it  existed  on the  first  day of the  Term  of this                            Agreement.  The Company  also  reserves  the right to                            increase  or  decrease  the price  per unit  based on                            Company   wide   changes   in  unit   prices  to  all                            distributors of the Company,  provided however,  that
--------------------------------------------------
Contract: LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGREEMENT
Labels: ['Price Restrictions']
TEXT:
 in  unit   prices  to  all                            distributors of the Company,  provided however,  that                            any price changes, other than those based on the CPI,                            shall be uniformly applied to all distributors of the                            Products   and  shall   reasonably   applied  to  all                            distributors  of the  Products  and shall  reasonably                            reflect Company's costs of manufacturing the Products                            and/or  market  demand  for  the  Products,  provided                            further  than any increase in price based upon market                            demand   shall   not  be  so  great  as  to   deprive                            Distributor  of  its  normal  and  customary   profit                            margin.  The Company agrees to exercise this right in                            good faith,  and  consider all  circumstances  of the
--------------------------------------------------

=================================================================
Unlimited/All-You-Can-Eat-License | training positives: 22
Contract: CORIOINC_07_20_2000-EX-10.5-LICENSE AND HOSTING AGREEMENT
Labels: ['Unlimited/All-You-Can-Eat-License']
TEXT:
        enhancements of the Software and MarketSite software used to operate the         MarketSite.net Service.

1.13    "UPGRADE(S)" means a release, function or version of the Software         designated as such by Commerce One which contains new features or         significant functional enhancements to the Software, which are indicated         by a change in the numeric identifier for the Software in the digit to         the left of the decimal, or a new release, function or version of the         MarketSite.net Service, which Upgrade is provided to Commerce One's         installed customer base for the Software and MarketSite software used to         operate the MarketSite.net Service. For the purposes of this Agreement,         "Maintenance and Support" means those services listed in EXHIBIT C and         the provision of Updates and Upgrades as called for by this Agreement

[*] Certain information on this page has been omitted and filed separately with     the Commission. Confidential treatment has been requested with respect to     the omitted portions.

                                     2

3 2.      GRANT OF RIGHTS.

2.1     Hosting Software License. Subject to the ter
--------------------------------------------------
Contract: CORIOINC_07_20_2000-EX-10.5-LICENSE AND HOSTING AGREEMENT
Labels: ['License Grant', 'Non-Transferable License', 'Unlimited/All-You-Can-Eat-License', 'Irrevocable Or Perpetual License']
TEXT:
   to (i) reproduce the Software in machine executable object code format         only for installation on the Corio Servers; (ii) install multiple copies         of the Software on Corio's Servers which will be made remotely         accessible to Corio's Customers for their subsequent use, (iii) permit         limited access to and use of the Software and MarketSite.net Service by         Customers through Corio Servers; (iv) sublicense an unlimited number of         Customers to access and use the Software and MarketSite.net Service only         through the installation on Corio servers; and (v) use Commerce One's         tools and utilities, subject to any restrictions placed on the Commerce         One by third party software providers, to modify and manage the         Software. Except as specifically authorized by this Agreement, no         license is granted under this Agreement to Corio to distribute the         Software to its Customers or for use other than as part of the Corio         Services.

2.2     Internal Use License. Subject to the terms and conditions of this         Agreement, Commerce One grants to Corio a nonexclusive, nontransferable         (except in accord
--------------------------------------------------

=================================================================
Source Code Escrow | training positives: 25
Contract: CORIOINC_07_20_2000-EX-10.5-LICENSE AND HOSTING AGREEMENT
Labels: ['Source Code Escrow']
TEXT:
obligation to provide Software support and maintenance to         Corio and its Customers shall survive any termination or expiration of         this Agreement, provided Corio continues to make its annual support and         maintenance payments as specified in this Agreement. Upon termination or         expiration of this Agreement, each party shall otherwise return or         destroy any Confidential Information of the other party provided,         however, Corio may retain any Confidential Information necessary for         Corio to continue supporting it's then-existing Customers.

12      SOURCE CODE ESCROW.

12.1    Escrow Account. Within sixty (60) days of the Effective Date, Commerce         One agrees to execute an escrow agreement by and among Corio, Commerce         One and a mutually acceptable escrow agent (the "ESCROW AGENT"). The         Escrow Agent shall require Commerce One to place in an

                                    10

11         escrow account in California a copy of the source code of the Software





     including all Updates and Upgrades thereto, documentation and similar         materials (the SOURCE CODE). The escrow agreement shall contain, at a
--------------------------------------------------
Contract: CORIOINC_07_20_2000-EX-10.5-LICENSE AND HOSTING AGREEMENT
Labels: ['License Grant', 'Non-Transferable License', 'Source Code Escrow']
TEXT:
Source Code         to Corio under the escrow agreement, Corio agrees to hold the Source         Code in confidence pursuant to the provisions contained in Section 10 of         this Agreement, and not to use them for any purpose other than those         purposes contemplated under Section 12.3 of this Agreement.

12.2    Release. Corio shall notify Commerce One in writing if it believes that         one of the following events (the "RELEASE CONDITIONS") has occurred and         that it intends to seek release of the Source Code from the escrow         account: (i) Commerce One's dissolution or ceasing to do business in the         normal course, or (ii) Commerce One's repeated and material breach of         its support and maintenance obligations under Section 5 of this         Agreement and such breach is not cured within sixty (60) days of receipt         of written notice thereof from Corio. If Commerce One notifies Corio in         writing that it disputes whether any such event has occurred, officers         of each of the parties shall negotiate for a period of ten (10) business         days to attempt to resolve the dispute. At the end of such ten (10)         business day
--------------------------------------------------

=================================================================
Most Favored Nation | training positives: 25
Contract: SENMIAOTECHNOLOGYLTD_02_19_2019-EX-10.5-Collaboration Agreement
Labels: ['Most Favored Nation']
TEXT:
1.10.2 The business (including, but not limited to, business decisions, management methods, operating strategies, incentive strategies, promotional information), operating, financial, technical, product, service information of any party obtained or received by the other party during the performance of this Agreement or during the term of this Agreement; 1.10.3 The other party's user profiles, information, etc.; 1.10.4 The processes and results of settlement of any dispute arising from this Agreement 1.11 "Intellectual Property Rights" refers to: (a) patents and patent applications; (b) trademarks, service marks, trade names, trade dress and domain names, and goodwill exclusively attached thereto; (c) copyrights, including the copyrights of computer software and the copyrights of the database; (d) secrets and proprietary information, including trade secrets and technical secrets; and (e) any rights similar to subparagraphs (a)-(d) provided in any law, whether or not any one of the foregoing has been applied for registration or registered. 1.12 "Personal Injury Compensation" refers to the compensation provided in the Interpretation of the Supreme People's Court on Several Issues Conc
--------------------------------------------------
Contract: SENMIAOTECHNOLOGYLTD_02_19_2019-EX-10.5-Collaboration Agreement
Labels: ['Most Favored Nation']
TEXT:
A and Party B and the Platform Rules. Party B shall provide the Driver User with long-term and stable rental sources and the most favorable financial leasing scheme, complete the vehicle leasing transactions with the Driver User through the Platform, and provide the Driver User with high-quality financial leasing services. 3. Rights and Obligations 3.1 Party A's rights and obligations: 3.1.1 Party A shall maintain and operate the Platform in accordance with the available technology, so that the Platform can operate normally, and Party B can use the Platform normally and conduct vehicle financial leasing transactions with the Driver User smoothly. 3.1.2 Party A shall reply to problems encountered by Party B during the registration in and use of the Platform in a timely manner. 3.1.3 Party A is entitled to inspect any information and materials submitted by Party B and the information generated by the use of the Platform from time to time. In case any problem or question is discovered in the aforesaid information or materials, Party A is entitled to take the following measures: 3.1.3.1 To request Party B to submit more information or documentary evidence; 3.1.3.2 To request Party B to
--------------------------------------------------

=================================================================
No-Solicit Of Customers | training positives: 33
Contract: LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGREEMENT
Labels: ['No-Solicit Of Customers', 'No-Solicit Of Employees']
TEXT:
onsolicitation.

                  (A)      During the Term of this Agreement and for a period of                            twelve (12) months  thereafter,  the  Distributor (on                            behalf of itself,  each of its affiliates and each of                            their respective representatives) agrees that it will                            not  directly  or  indirectly  solicit  or  hire  any                            executive,  managerial  or technical  employee of the                            Company or any of its affiliates.

                  (B)      Distributor further agrees that it will not interfere                            with or  otherwise  disrupt  the  business  relations                            between the Company or nay of its  affiliates and any                            of their current or prospective customers,  suppliers                            or distributors, during the

                                    Page -11-


--------------------------------------------------
Contract: LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGREEMENT
Labels: ['No-Solicit Of Customers']
TEXT:
  or distributors, during the

                                    Page -11-

                           Term of the  Agreement  and for a period of  eighteen





                           (18) months thereafter,  nor will Distributor solicit                            any  customer  or  potential  customer  of Company to                            purchase a competitive product during that period.

         5.8.     Nonpublic Information. The Distributor acknowledges that is it                   aware that the  securities  laws  prohibit  any person who has                   material, non-public information concerning the Company or the                   matters  which  are  the  subject  of  this   Agreement   from                   purchasing  or selling  securities of the Company (or options,                   warrants and rights relating  thereto) and from  communicating                   such  information to any other person under  circumstances  in                   which it is reasonably  foreseeable that such person is likely                   to purchase or sell such securities.

6.       INTERPRETATION AND ENFORCEMENT

         6.1      Assignment
--------------------------------------------------

=================================================================
Third Party Beneficiary | training positives: 33
Contract: PfHospitalityGroupInc_20150923_10-12G_EX-10.1_9266710_EX-10.1_Franchise Agreement3
Labels: ['Third Party Beneficiary']
TEXT:
2) years from the date of: (a) a transfer permitted under Section 14 of the Franchise Agreement; (b) expiration or termination of the Franchise Agreement (regardless of the cause for termination); (c) termination of Member's employment with Franchisee; and/or (d) a final order of a duly authorized arbitrator, panel of arbitrators, or a court of competent jurisdiction (after all appeals have been taken) with respect to any of the foregoing or with respect to the enforcement of this Agreement; either directly or indirectly (through, on behalf of, or in conjunction with any persons, partnership, corporation or entity). 3. Injunctive Relief. Member acknowledges that any failure to comply with the requirements of this Agreement will cause Franchisor irreparable injury, and Member agrees to pay all court costs and reasonable attorney's fees incurred by Franchisor in obtaining specific performance of, or an injunction against violation of, the requirements of this Agreement. 4. Severability. All agreements and covenants contained herein are severable. If any of them, or any part or parts of them, shall be held invalid by any court of competent jurisdiction for any reason, then the Member
--------------------------------------------------
Contract: CUROGROUPHOLDINGSCORP_05_04_2020-EX-10.3-SERVICING AGREEMENT
Labels: ['Covenant Not To Sue', 'Third Party Beneficiary']
TEXT:
e-mail") or E-Fax, or otherwise to or from an electronic system or other equivalent service.

Section 19. Severability. Any provision of this Agreement that is prohibited or unenforceable in any jurisdiction shall be ineffective to the extent of such prohibition or unenforceability without invalidating the remaining provisions hereof and any such prohibition or unenforceability in any jurisdiction shall not invalidate or render unenforceable such provision in any other jurisdiction.

Section 20. Non-Petition. Notwithstanding any prior termination of the Owner or this Agreement, the Servicer shall not at any time with respect to the Owner, acquiesce, petition or otherwise invoke or cause the Owner to invoke the process of any court or governmental authority for the purpose of commencing or sustaining a case against the Owner under any federal or state bankruptcy, insolvency or similar law or appointing a receiver, conservator, liquidator, assignee, trustee, custodian, sequestrator or other similar official of the Owner or any substantial part of its property, or ordering the winding up or liquidation of the affairs of the Owner.

Section 21. Third-Party Beneficiary. Notwithstanding
--------------------------------------------------

=================================================================
Non-Disparagement | training positives: 38
Contract: INTERNATIONALFASTFOODCORP_04_04_1997-EX-99-FRANCHISE AGREEMENT
Labels: ['Non-Disparagement', 'Covenant Not To Sue']
TEXT:
IDENTIALITY OF TRADE SECRETS. The Franchisee agrees that all materials  made available to the Franchise and all  disclosures  made to the Franchisee,  and not to the general public, by or at the direction of BKC at any time before or during the term of this  Agreement,  including  the MOD Manual in its entirety and any translations thereof, are to be considered trade secrets of BKC for purpose of this Agreement and shall be kept confidential and used by the Franchisee only in the operation of the Franchised Restaurant and other licensed Burger King  Restaurants.  The Franchise  agrees not to divulge any of the trade secrets to any person other than the Franchisee's employees and then only to the extent  necessary for the operation of the  Franchised  Restaurant,  an d not to permit anyone to reproduce, copy or exhibit any portion of the MOD Manual or any other  confidential  or proprietary  information  received from BKC,  except for translating  from English to the language of the country in which the Franchised Restaurant is located, if the Franchisee's  employees cannot read and understand English.

                                      16

            11.1.4 REGISTERED USER AGR
--------------------------------------------------
Contract: PelicanDeliversInc_20200211_S-1_EX-10.3_11975895_EX-10.3_Development Agreement2
Labels: ['Non-Disparagement', 'Termination For Convenience']
TEXT:
local law or regulation; or (d) any claim made against Client asserting a violation of any third party intellectual property right pertaining to the Subject Program.

20

Source: PELICAN DELIVERS, INC., S-1, 2/11/2020





10.3 NON DISPARAGEMENT CLAUSE The Client and the Designer both agree to never to disparage or speak ill of the other party to anyone and or post negative or disparaging comments Online regarding any of the Designer's products, services, affiliates, subsidiaries, officers, directors, employees or shareholders, and will take reasonable steps to prevent and will not knowingly permit any of their respective employees or agents to, disparage or speak ill of such persons. For purposes of this Section, "disparage" shall mean any negative statement whether written or oral, about Seattle Software Developers, Inc., Dot Com LLC. and or any of its affiliates. The Client and Designer both agree not to post on defamatory websites or review websites any negative posts concerning each other, the names of our companies, and our employees. Both the Client and the Designer both agree and acknowledge that this non-disparagement provision is a material term of this Agreement, the abs
--------------------------------------------------

=================================================================
Affiliate License-Licensor | training positives: 39
Contract: ENERGOUSCORP_03_16_2017-EX-10.24-STRATEGIC ALLIANCE AGREEMENT
Labels: ['Affiliate License-Licensor']
TEXT:

Train the model

In [39]:

import os, gc, json, time, random
import numpy as np
import pandas as pd
import torch

from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from sklearn.metrics import f1_score, precision_score, recall_score

# ==========================================
# CONFIGURATION
# ==========================================

MODEL_NAME = "microsoft/deberta-v3-base"

ROOT = "/content/cuad_deberta_v2"
BEST_PATH = ROOT + "/best_model"

MAX_LENGTH = 512
BATCH_SIZE = 4
GRAD_ACCUM = 2
EVAL_BATCH_SIZE = 16

TIME_LIMIT_MINUTES = 15
MAX_STEPS = 5000
EVAL_EVERY = 250

LEARNING_RATE = 1.5e-5
SEED = 42

os.makedirs(ROOT, exist_ok=True)

assert torch.cuda.is_available(), "Enable GPU in Colab"

DEVICE = torch.device("cuda")

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

# ==========================================
# TOKENIZER + DATASETS
# ==========================================

new_tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

train_ds = ContractDataset(
    train_chunks["chunk_text"].fillna("").tolist(),
    y_train,
    new_tokenizer,
    max_length=MAX_LENGTH
)

val_ds = ContractDataset(
    val_chunks["chunk_text"].fillna("").tolist(),
    y_val,
    new_tokenizer,
    max_length=MAX_LENGTH
)

train_loader = DataLoader(
    train_ds,
    batch_size=BATCH_SIZE,
    shuffle=True,
    pin_memory=True
)

val_loader = DataLoader(
    val_ds,
    batch_size=EVAL_BATCH_SIZE,
    shuffle=False,
    pin_memory=True
)

# ==========================================
# MODEL
# ==========================================

gc.collect()
torch.cuda.empty_cache()

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=len(categories),
    problem_type="multi_label_classification"
).to(DEVICE)

# Moderate positive weighting
y = np.asarray(y_train)

positive_counts = y.sum(axis=0)
negative_counts = len(y) - positive_counts

weights = np.clip(
    np.sqrt(
        negative_counts / np.maximum(positive_counts, 1)
    ),
    1,
    3
)

loss_fn = torch.nn.BCEWithLogitsLoss(
    pos_weight=torch.tensor(
        weights,
        dtype=torch.float32,
        device=DEVICE
    )
)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=0.01
)

scaler = torch.amp.GradScaler("cuda")

# ==========================================
# EVALUATION
# ==========================================

@torch.no_grad()
def evaluate():
    model.eval()

    probabilities = []
    labels = []

    for batch in val_loader:
        inputs = {
            k: v.to(DEVICE)
            for k, v in batch.items()
            if k != "labels"
        }

        with torch.autocast("cuda", dtype=torch.float16):
            logits = model(**inputs).logits

        probabilities.append(
            torch.sigmoid(logits.float()).cpu().numpy()
        )
        labels.append(batch["labels"].numpy())

    probabilities = np.concatenate(probabilities)
    labels = np.concatenate(labels).astype(int)

    best = None

    for threshold in np.arange(0.10, 0.801, 0.025):
        predictions = (
            probabilities >= threshold
        ).astype(int)

        metrics = {
            "threshold": float(threshold),
            "micro_f1": float(f1_score(
                labels,
                predictions,
                average="micro",
                zero_division=0
            )),
            "macro_f1": float(f1_score(
                labels,
                predictions,
                average="macro",
                zero_division=0
            )),
            "precision": float(precision_score(
                labels,
                predictions,
                average="micro",
                zero_division=0
            )),
            "recall": float(recall_score(
                labels,
                predictions,
                average="micro",
                zero_division=0
            )),
            "categories_detected": int(
                (
                    f1_score(
                        labels,
                        predictions,
                        average=None,
                        zero_division=0
                    ) > 0
                ).sum()
            )
        }

        if best is None or (
            metrics["micro_f1"] > best["micro_f1"]
        ):
            best = metrics

    model.train()

    return best

# ==========================================
# TRAINING
# ==========================================

start_time = time.monotonic()
step = 0
best_micro = -1
history = []

model.train()
optimizer.zero_grad(set_to_none=True)

print("Starting DeBERTa training...")
print("GPU:", torch.cuda.get_device_name(0))

stop = False

while not stop:

    for batch in train_loader:

        inputs = {
            k: v.to(DEVICE)
            for k, v in batch.items()
            if k != "labels"
        }

        labels = batch["labels"].to(DEVICE).float()

        with torch.autocast("cuda", dtype=torch.float16):
            logits = model(**inputs).logits
            loss = loss_fn(
                logits.float(),
                labels
            ) / GRAD_ACCUM

        scaler.scale(loss).backward()

        step += 1

        if step % GRAD_ACCUM == 0:
            scaler.unscale_(optimizer)

            torch.nn.utils.clip_grad_norm_(
                model.parameters(), 1.0
            )

            scaler.step(optimizer)
            scaler.update()

            optimizer.zero_grad(set_to_none=True)

        if step % 50 == 0:
            elapsed = (
                time.monotonic() - start_time
            ) / 60

            print(
                f"Step {step} | "
                f"Loss {loss.item()*GRAD_ACCUM:.4f} | "
                f"Elapsed {elapsed:.1f} min"
            )

        if step % EVAL_EVERY == 0:

            metrics = evaluate()

            history.append({
                "step": step,
                **metrics
            })

            print("\nVALIDATION", step)
            print(metrics)

            if metrics["micro_f1"] > best_micro:

                best_micro = metrics["micro_f1"]

                model.save_pretrained(
                    BEST_PATH,
                    safe_serialization=True
                )

                new_tokenizer.save_pretrained(
                    BEST_PATH
                )

                with open(
                    BEST_PATH + "/metadata.json", "w"
                ) as f:
                    json.dump({
                        "step": step,
                        "metrics": metrics,
                        "categories": list(categories),
                        "max_length": MAX_LENGTH
                    }, f, indent=2)

                print("BEST CHECKPOINT SAVED")

        elapsed = (
            time.monotonic() - start_time
        ) / 60

        if (
            elapsed >= TIME_LIMIT_MINUTES
            or step >= MAX_STEPS
        ):
            stop = True
            break

# If time limit ended before first evaluation,
# still save a usable checkpoint.
if best_micro < 0:
    metrics = evaluate()
    best_micro = metrics["micro_f1"]
    model.save_pretrained(BEST_PATH)
    new_tokenizer.save_pretrained(BEST_PATH)
    with open(BEST_PATH + "/metadata.json", "w") as f:
        json.dump({
            "step": step,
            "metrics": metrics,
            "categories": list(categories),
            "max_length": MAX_LENGTH
        }, f, indent=2)

pd.DataFrame(history).to_csv(
    ROOT + "/history.csv",
    index=False
)

print("\nTRAINING COMPLETE")
print("Steps:", step)
print("Best validation micro-F1:", best_micro)
print("Saved at:", BEST_PATH)

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/579 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

/usr/local/lib/python3.13/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

pytorch_model.bin:   0%|          | 0.00/371M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/371M [00:00<?, ?B/s]

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Starting DeBERTa training...
GPU: Tesla T4
Step 50 | Loss 0.5122 | Elapsed 0.2 min
Step 100 | Loss 0.3698 | Elapsed 0.5 min
Step 150 | Loss 0.2323 | Elapsed 0.7 min
Step 200 | Loss 0.1446 | Elapsed 0.9 min
Step 250 | Loss 0.1838 | Elapsed 1.1 min

VALIDATION 250
{'threshold': 0.125, 'micro_f1': 0.05775216901781575, 'macro_f1': 0.01042852885618692, 'precision': 0.03130834410455263, 'recall': 0.37169650468883203, 'categories_detected': 7}
BEST CHECKPOINT SAVED
Step 300 | Loss 0.2220 | Elapsed 2.5 min
Step 350 | Loss 0.3154 | Elapsed 2.7 min
Step 400 | Loss 0.1029 | Elapsed 2.9 min
Step 450 | Loss 0.0584 | Elapsed 3.1 min
Step 500 | Loss 0.2367 | Elapsed 3.4 min

VALIDATION 500
{'threshold': 0.1, 'micro_f1': 0.07864726700747149, 'macro_f1': 0.0102400974087744, 'precision': 0.072992700729927, 'recall': 0.08525149190110827, 'categories_detected': 2}
BEST CHECKPOINT SAVED
Step 550 | Loss 0.4481 | Elapsed 4.8 min
Step 600 | Loss 0.0533 | Elapsed 5.0 min
Step 650 | Loss 0.0484 | Elapsed 5.2 min
Step 700 | Loss 0.3100 | Elapsed 5.5 min
Step 750 | Loss 0.0637 | Elapsed 5.7 min

VALIDATION 750
{'threshold': 0.175, 'micro_f1': 0.2343529411764706, 'macro_f1': 0.05699850823803362, 'precision': 0.2615546218487395, 'recall': 0.21227621483375958, 'categories_detected': 5}
BEST CHECKPOINT SAVED
Step 800 | Loss 0.0419 | Elapsed 7.1 min
Step 850 | Loss 0.5041 | Elapsed 7.3 min
Step 900 | Loss 0.2413 | Elapsed 7.6 min
Step 950 | Loss 0.0898 | Elapsed 7.8 min
Step 1000 | Loss 0.1983 | Elapsed 8.0 min

VALIDATION 1000
{'threshold': 0.22499999999999998, 'micro_f1': 0.2957983193277311, 'macro_f1': 0.08718345716557381, 'precision': 0.43137254901960786, 'recall': 0.22506393861892582, 'categories_detected': 6}
BEST CHECKPOINT SAVED
Step 1050 | Loss 0.3241 | Elapsed 9.5 min
Step 1100 | Loss 0.2208 | Elapsed 9.8 min
Step 1150 | Loss 0.0817 | Elapsed 10.0 min
Step 1200 | Loss 0.1751 | Elapsed 10.2 min
Step 1250 | Loss 0.0337 | Elapsed 10.5 min

VALIDATION 1250
{'threshold': 0.32499999999999996, 'micro_f1': 0.3256597417181359, 'macro_f1': 0.10187789625265115, 'precision': 0.4769736842105263, 'recall': 0.24722932651321397, 'categories_detected': 7}
BEST CHECKPOINT SAVED
Step 1300 | Loss 0.3557 | Elapsed 12.0 min
Step 1350 | Loss 0.1428 | Elapsed 12.2 min
Step 1400 | Loss 0.1889 | Elapsed 12.4 min
Step 1450 | Loss 0.2192 | Elapsed 12.7 min
Step 1500 | Loss 0.0288 | Elapsed 12.9 min

VALIDATION 1500
{'threshold': 0.3999999999999999, 'micro_f1': 0.35914489311163894, 'macro_f1': 0.10323929092202773, 'precision': 0.4055793991416309, 'recall': 0.32225063938618925, 'categories_detected': 8}
BEST CHECKPOINT SAVED
Step 1550 | Loss 0.1946 | Elapsed 14.3 min
Step 1600 | Loss 0.1662 | Elapsed 14.5 min
Step 1650 | Loss 0.1754 | Elapsed 14.7 min
Step 1700 | Loss 0.0245 | Elapsed 15.0 min

TRAINING COMPLETE
Steps: 1711
Best validation micro-F1: 0.35914489311163894
Saved at: /content/cuad_deberta_v2/best_model

In [30]:

import os, gc, json, time, random, shutil
import numpy as np
import pandas as pd
import torch

from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from sklearn.metrics import f1_score, precision_score, recall_score

# ============================================================
# 1. CONFIGURATION
# ============================================================

SEED = 42
MODEL_NAME = "distilbert/distilroberta-base"
MAX_LENGTH = 512
BATCH_SIZE = 8

# 10-minute approximate budget
TRAIN_TIME_LIMIT = 525
EVAL_EVERY = 400
MAX_STEPS = 5000

# Learning rate progression based on your successful runs
LR_PHASES = [
    (1800, 2e-5),
    (3000, 1e-5),
    (5000, 5e-6)
]

WEIGHT_CAP = 3.0

ROOT = "/content/cuad_fresh_training"
BEST_MICRO = ROOT + "/best_micro"
BEST_MACRO = ROOT + "/best_macro"
HISTORY_PATH = ROOT + "/history.csv"

os.makedirs(ROOT, exist_ok=True)

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)
assert DEVICE.type == "cuda", "Enable GPU in Colab."

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

start_time = time.monotonic()

# ============================================================
# 2. REBUILD DATASETS AT 512 TOKENS
# ============================================================

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

train_dataset = ContractDataset(
    train_chunks["chunk_text"].fillna("").tolist(),
    y_train,
    tokenizer,
    max_length=MAX_LENGTH
)

val_dataset = ContractDataset(
    val_chunks["chunk_text"].fillna("").tolist(),
    y_val,
    tokenizer,
    max_length=MAX_LENGTH
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False,
    pin_memory=True
)

print("Training examples:", len(train_dataset))
print("Validation examples:", len(val_dataset))
print("Max token length:", MAX_LENGTH)

# ============================================================
# 3. FRESH MODEL
# ============================================================

if "model" in globals():
    del model

gc.collect()
torch.cuda.empty_cache()

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=len(categories),
    problem_type="multi_label_classification"
).to(DEVICE)

# ============================================================
# 4. CLASS-WEIGHTED LOSS
# ============================================================

y_train_np = np.asarray(y_train, dtype=np.float32)

positives = y_train_np.sum(axis=0)
negatives = len(y_train_np) - positives

class_weights = np.clip(
    np.sqrt(negatives / np.maximum(positives, 1)),
    1.0,
    WEIGHT_CAP
)

criterion = torch.nn.BCEWithLogitsLoss(
    pos_weight=torch.tensor(
        class_weights,
        dtype=torch.float32,
        device=DEVICE
    )
)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=2e-5,
    weight_decay=0.01
)

scaler = torch.amp.GradScaler("cuda")

# ============================================================
# 5. EVALUATION
# ============================================================

@torch.no_grad()
def evaluate_model(model):
    model.eval()

    all_probs = []
    all_true = []

    for batch in val_loader:
        inputs = {
            k: v.to(DEVICE, non_blocking=True)
            for k, v in batch.items()
            if k != "labels"
        }

        with torch.autocast("cuda", dtype=torch.float16):
            logits = model(**inputs).logits

        all_probs.append(
            torch.sigmoid(logits.float()).cpu().numpy()
        )
        all_true.append(batch["labels"].numpy())

    probs = np.concatenate(all_probs)
    true = np.concatenate(all_true).astype(int)

    # One global threshold: avoids rare-label overprediction
    best = None

    for threshold in np.arange(0.10, 0.801, 0.025):
        pred = (probs >= threshold).astype(int)

        micro = f1_score(
            true, pred,
            average="micro",
            zero_division=0
        )

        macro = f1_score(
            true, pred,
            average="macro",
            zero_division=0
        )

        if best is None or micro > best["micro_f1"]:
            per_class = f1_score(
                true, pred,
                average=None,
                zero_division=0
            )

            best = {
                "threshold": float(threshold),
                "micro_f1": float(micro),
                "macro_f1": float(macro),
                "precision": float(precision_score(
                    true, pred,
                    average="micro",
                    zero_division=0
                )),
                "recall": float(recall_score(
                    true, pred,
                    average="micro",
                    zero_division=0
                )),
                "categories_detected": int(
                    (per_class > 0).sum()
                ),
                "predicted_positives": int(pred.sum())
            }

    # Separately find the threshold that maximizes macro-F1,
    # subject to minimum precision and micro-F1 requirements.
    macro_candidate = None

    for threshold in np.arange(0.10, 0.801, 0.025):
        pred = (probs >= threshold).astype(int)

        micro = f1_score(
            true, pred,
            average="micro",
            zero_division=0
        )
        macro = f1_score(
            true, pred,
            average="macro",
            zero_division=0
        )
        precision = precision_score(
            true, pred,
            average="micro",
            zero_division=0
        )

        if precision < 0.35 or micro < 0.40:
            continue

        if (
            macro_candidate is None
            or macro > macro_candidate["macro_f1"]
        ):
            per_class = f1_score(
                true, pred,
                average=None,
                zero_division=0
            )

            macro_candidate = {
                "threshold": float(threshold),
                "micro_f1": float(micro),
                "macro_f1": float(macro),
                "precision": float(precision),
                "recall": float(recall_score(
                    true, pred,
                    average="micro",
                    zero_division=0
                )),
                "categories_detected": int(
                    (per_class > 0).sum()
                ),
                "predicted_positives": int(pred.sum())
            }

    model.train()
    return best, macro_candidate

# ============================================================
# 6. CHECKPOINT SAVING
# ============================================================

def save_checkpoint(path, metrics, step, objective):
    os.makedirs(path, exist_ok=True)

    model.save_pretrained(path)
    tokenizer.save_pretrained(path)

    with open(path + "/metadata.json", "w") as f:
        json.dump({
            "step": step,
            "objective": objective,
            "metrics": metrics,
            "categories": list(categories),
            "max_length": MAX_LENGTH,
            "weight_cap": WEIGHT_CAP,
            "seed": SEED
        }, f, indent=2)

# ============================================================
# 7. TRAINING
# ============================================================

best_micro_f1 = -1
best_macro_f1 = -1

history = []
step = 0
losses = []

model.train()

def learning_rate_at(step):
    for boundary, lr in LR_PHASES:
        if step < boundary:
            return lr
    return LR_PHASES[-1][1]

def run_validation(step):
    global best_micro_f1, best_macro_f1

    micro_metrics, macro_metrics = evaluate_model(model)

    row = {
        "step": step,
        "lr": learning_rate_at(step - 1),
        **micro_metrics,
        "macro_optimized_f1": (
            macro_metrics["macro_f1"]
            if macro_metrics is not None else np.nan
        )
    }
    history.append(row)

    print(
        f"\nVALIDATION @ {step} | "
        f"Micro={micro_metrics['micro_f1']:.4f} | "
        f"Macro={micro_metrics['macro_f1']:.4f} | "
        f"Precision={micro_metrics['precision']:.4f} | "
        f"Recall={micro_metrics['recall']:.4f} | "
        f"Categories={micro_metrics['categories_detected']}"
    )

    if micro_metrics["micro_f1"] > best_micro_f1:
        best_micro_f1 = micro_metrics["micro_f1"]
        save_checkpoint(
            BEST_MICRO, micro_metrics, step, "micro"
        )
        print("NEW BEST MICRO MODEL SAVED")

    if (
        macro_metrics is not None
        and macro_metrics["macro_f1"] > best_macro_f1
    ):
        best_macro_f1 = macro_metrics["macro_f1"]
        save_checkpoint(
            BEST_MACRO, macro_metrics, step, "macro"
        )
        print("NEW BEST MACRO MODEL SAVED")

    pd.DataFrame(history).to_csv(
        HISTORY_PATH, index=False
    )

while step < MAX_STEPS:

    for batch in train_loader:

        if step >= MAX_STEPS:
            break

        if time.monotonic() - start_time >= TRAIN_TIME_LIMIT:
            break

        lr = learning_rate_at(step)

        for group in optimizer.param_groups:
            group["lr"] = lr

        inputs = {
            k: v.to(DEVICE, non_blocking=True)
            for k, v in batch.items()
            if k != "labels"
        }

        labels = batch["labels"].to(
            DEVICE, non_blocking=True
        ).float()

        optimizer.zero_grad(set_to_none=True)

        with torch.autocast("cuda", dtype=torch.float16):
            logits = model(**inputs).logits
            loss = criterion(logits.float(), labels)

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)

        torch.nn.utils.clip_grad_norm_(
            model.parameters(), 1.0
        )

        scaler.step(optimizer)
        scaler.update()

        step += 1
        losses.append(loss.item())

        if step % 100 == 0:
            print(
                f"Step {step}/{MAX_STEPS} | "
                f"LR {lr:.1e} | "
                f"Loss {np.mean(losses[-100:]):.4f} | "
                f"Elapsed "
                f"{(time.monotonic()-start_time)/60:.2f} min"
            )

        if step % EVAL_EVERY == 0:
            run_validation(step)

    if time.monotonic() - start_time >= TRAIN_TIME_LIMIT:
        break

# Final evaluation for unfinished interval
if step > 0 and step % EVAL_EVERY != 0:
    run_validation(step)

# ============================================================
# 8. FINAL RESULTS
# ============================================================

results_df = pd.DataFrame(history)

print("\n" + "=" * 60)
print("FINAL TRAINING RESULTS")
print("=" * 60)

display(results_df)

print("Best micro-F1:", round(best_micro_f1, 4))
print("Best macro-F1:", round(best_macro_f1, 4))
print("Steps completed:", step)
print(
    "Runtime:",
    round((time.monotonic()-start_time)/60, 2),
    "minutes"
)

print("\nBest overall model:", BEST_MICRO)
print("Best category-balanced model:", BEST_MACRO)
print("Training history:", HISTORY_PATH)

Training examples: 11500
Validation examples: 1998
Max token length: 512

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at distilbert/distilroberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Step 100/5000 | LR 2.0e-05 | Loss 0.3624 | Elapsed 0.44 min
Step 200/5000 | LR 2.0e-05 | Loss 0.2039 | Elapsed 0.65 min
Step 300/5000 | LR 2.0e-05 | Loss 0.1810 | Elapsed 0.85 min
Step 400/5000 | LR 2.0e-05 | Loss 0.1796 | Elapsed 1.06 min

VALIDATION @ 400 | Micro=0.2123 | Macro=0.0475 | Precision=0.3019 | Recall=0.1637 | Categories=5
NEW BEST MICRO MODEL SAVED
Step 500/5000 | LR 2.0e-05 | Loss 0.1813 | Elapsed 1.58 min
Step 600/5000 | LR 2.0e-05 | Loss 0.1637 | Elapsed 1.79 min
Step 700/5000 | LR 2.0e-05 | Loss 0.1699 | Elapsed 2.00 min
Step 800/5000 | LR 2.0e-05 | Loss 0.1728 | Elapsed 2.22 min

VALIDATION @ 800 | Micro=0.2440 | Macro=0.0607 | Precision=0.4652 | Recall=0.1654 | Categories=5
NEW BEST MICRO MODEL SAVED
Step 900/5000 | LR 2.0e-05 | Loss 0.1558 | Elapsed 2.75 min
Step 1000/5000 | LR 2.0e-05 | Loss 0.1638 | Elapsed 2.96 min
Step 1100/5000 | LR 2.0e-05 | Loss 0.1441 | Elapsed 3.18 min
Step 1200/5000 | LR 2.0e-05 | Loss 0.1420 | Elapsed 3.40 min

VALIDATION @ 1200 | Micro=0.3698 | Macro=0.1116 | Precision=0.4692 | Recall=0.3052 | Categories=9
NEW BEST MICRO MODEL SAVED
Step 1300/5000 | LR 2.0e-05 | Loss 0.1308 | Elapsed 3.78 min
Step 1400/5000 | LR 2.0e-05 | Loss 0.1319 | Elapsed 4.00 min
Step 1500/5000 | LR 2.0e-05 | Loss 0.1196 | Elapsed 4.22 min
Step 1600/5000 | LR 2.0e-05 | Loss 0.1132 | Elapsed 4.44 min

VALIDATION @ 1600 | Micro=0.4827 | Macro=0.2012 | Precision=0.5624 | Recall=0.4228 | Categories=14
NEW BEST MICRO MODEL SAVED
NEW BEST MACRO MODEL SAVED
Step 1700/5000 | LR 2.0e-05 | Loss 0.1062 | Elapsed 5.17 min
Step 1800/5000 | LR 2.0e-05 | Loss 0.1120 | Elapsed 5.39 min
Step 1900/5000 | LR 1.0e-05 | Loss 0.1005 | Elapsed 5.61 min
Step 2000/5000 | LR 1.0e-05 | Loss 0.1094 | Elapsed 5.83 min

VALIDATION @ 2000 | Micro=0.5079 | Macro=0.2658 | Precision=0.5059 | Recall=0.5098 | Categories=22
NEW BEST MICRO MODEL SAVED
NEW BEST MACRO MODEL SAVED
Step 2100/5000 | LR 1.0e-05 | Loss 0.1018 | Elapsed 6.47 min
Step 2200/5000 | LR 1.0e-05 | Loss 0.0978 | Elapsed 6.68 min
Step 2300/5000 | LR 1.0e-05 | Loss 0.1005 | Elapsed 6.90 min
Step 2400/5000 | LR 1.0e-05 | Loss 0.0952 | Elapsed 7.12 min

VALIDATION @ 2400 | Micro=0.5444 | Macro=0.2608 | Precision=0.5994 | Recall=0.4987 | Categories=19
NEW BEST MICRO MODEL SAVED
NEW BEST MACRO MODEL SAVED
Step 2500/5000 | LR 1.0e-05 | Loss 0.1004 | Elapsed 7.67 min
Step 2600/5000 | LR 1.0e-05 | Loss 0.1025 | Elapsed 7.89 min
Step 2700/5000 | LR 1.0e-05 | Loss 0.0925 | Elapsed 8.11 min
Step 2800/5000 | LR 1.0e-05 | Loss 0.1001 | Elapsed 8.33 min

VALIDATION @ 2800 | Micro=0.5613 | Macro=0.2766 | Precision=0.6006 | Recall=0.5269 | Categories=19
NEW BEST MICRO MODEL SAVED
NEW BEST MACRO MODEL SAVED

============================================================
FINAL TRAINING RESULTS
============================================================

,step,lr,threshold,micro_f1,macro_f1,precision,recall,categories_detected,predicted_positives,macro_optimized_f1
0,400,0.00002,0.225,0.212272,0.047481,0.301887,0.163683,5,636,NaN
1,800,0.00002,0.225,0.244025,0.060685,0.465228,0.165388,5,417,NaN
2,1200,0.00002,0.350,0.369835,0.111625,0.469201,0.305200,9,763,NaN
3,1600,0.00002,0.475,0.482725,0.201229,0.562358,0.422847,14,882,0.217928
4,2000,0.00001,0.425,0.507856,0.265784,0.505922,0.509804,22,1182,0.277652
5,2400,0.00001,0.550,0.544439,0.260830,0.599385,0.498721,19,976,0.285966
6,2800,0.00001,0.475,0.561308,0.276646,0.600583,0.526854,19,1029,0.331821

Best micro-F1: 0.5613
Best macro-F1: 0.3318
Steps completed: 2800
Runtime: 8.81 minutes

Best overall model: /content/cuad_fresh_training/best_micro
Best category-balanced model: /content/cuad_fresh_training/best_macro
Training history: /content/cuad_fresh_training/history.csv

In [32]:

import os, json
import numpy as np
import pandas as pd
import torch

from torch.utils.data import DataLoader
from transformers import AutoModelForSequenceClassification
from sklearn.metrics import f1_score, precision_score, recall_score

MODEL_PATH = "/content/cuad_fresh_training/best_micro"
OUTPUT_PATH = "/content/cuad_fresh_training/calibration"
os.makedirs(OUTPUT_PATH, exist_ok=True)

with open(MODEL_PATH + "/metadata.json") as f:
    metadata = json.load(f)

base_threshold = float(metadata["metrics"]["threshold"])

m = AutoModelForSequenceClassification.from_pretrained(
    MODEL_PATH
).to(DEVICE)
m.eval()

loader = DataLoader(
    val_dataset, batch_size=32, shuffle=False
)

probs_list = []
true_list = []

with torch.no_grad():
    for batch in loader:
        inputs = {
            k: v.to(DEVICE)
            for k, v in batch.items()
            if k != "labels"
        }

        with torch.autocast("cuda", dtype=torch.float16):
            logits = m(**inputs).logits

        probs_list.append(
            torch.sigmoid(logits.float()).cpu().numpy()
        )
        true_list.append(batch["labels"].numpy())

probs = np.concatenate(probs_list)
true = np.concatenate(true_list).astype(int)

del m
torch.cuda.empty_cache()

def score(thresholds):
    pred = (probs >= thresholds).astype(int)

    return {
        "micro_f1": f1_score(
            true, pred, average="micro", zero_division=0
        ),
        "macro_f1": f1_score(
            true, pred, average="macro", zero_division=0
        ),
        "precision": precision_score(
            true, pred, average="micro", zero_division=0
        ),
        "recall": recall_score(
            true, pred, average="micro", zero_division=0
        ),
        "categories_detected": int(
            (f1_score(
                true, pred, average=None, zero_division=0
            ) > 0).sum()
        ),
        "predicted_positives": int(pred.sum())
    }

# Coordinate-descent optimization:
# optimize the combined objective rather than each class alone.
#
# Constraints:
# - micro-F1 cannot fall more than 0.02 below baseline
# - total predictions cannot exceed 1.5x baseline
# - minimum 10 validation positives before class-specific tuning

base = np.full(len(categories), base_threshold)
base_metrics = score(base)

thresholds = base.copy()

def objective(metrics):
    if metrics["micro_f1"] < base_metrics["micro_f1"] - 0.02:
        return -1e9

    if metrics["predicted_positives"] > (
        base_metrics["predicted_positives"] * 1.5
    ):
        return -1e9

    return (
        0.65 * metrics["micro_f1"]
        + 0.35 * metrics["macro_f1"]
    )

candidates = np.arange(0.15, 0.751, 0.025)

for iteration in range(3):
    for j in range(len(categories)):

        if true[:, j].sum() < 10:
            continue

        current_best = objective(score(thresholds))
        best_t = thresholds[j]

        for t in candidates:
            trial = thresholds.copy()
            trial[j] = t

            value = objective(score(trial))

            if value > current_best + 1e-8:
                current_best = value
                best_t = t

        thresholds[j] = best_t

    print(
        f"Iteration {iteration+1}:",
        score(thresholds)
    )

final_metrics = score(thresholds)

print("\nBASELINE:", base_metrics)
print("CALIBRATED:", final_metrics)

threshold_table = pd.DataFrame({
    "category": categories,
    "threshold": thresholds,
    "validation_positives": true.sum(axis=0)
})

display(threshold_table)

with open(OUTPUT_PATH + "/thresholds.json", "w") as f:
    json.dump({
        "model_path": MODEL_PATH,
        "thresholds": thresholds.tolist(),
        "metrics": final_metrics
    }, f, indent=2)

threshold_table.to_csv(
    OUTPUT_PATH + "/thresholds.csv",
    index=False
)

print("\nSaved calibration to:", OUTPUT_PATH)

Iteration 1: {'micro_f1': 0.63003663003663, 'macro_f1': 0.3985169808084398, 'precision': 0.6805143422354105, 'recall': 0.5865302642796248, 'categories_detected': 28, 'predicted_positives': 1011}
Iteration 2: {'micro_f1': 0.6308539944903582, 'macro_f1': 0.39716196725830427, 'precision': 0.6835820895522388, 'recall': 0.5856777493606138, 'categories_detected': 28, 'predicted_positives': 1005}
Iteration 3: {'micro_f1': 0.6308539944903582, 'macro_f1': 0.39716196725830427, 'precision': 0.6835820895522388, 'recall': 0.5856777493606138, 'categories_detected': 28, 'predicted_positives': 1005}

BASELINE: {'micro_f1': 0.5613079019073569, 'macro_f1': 0.2766462519330046, 'precision': 0.6005830903790087, 'recall': 0.5268542199488491, 'categories_detected': 19, 'predicted_positives': 1029}
CALIBRATED: {'micro_f1': 0.6308539944903582, 'macro_f1': 0.39716196725830427, 'precision': 0.6835820895522388, 'recall': 0.5856777493606138, 'categories_detected': 28, 'predicted_positives': 1005}

                              category  threshold  validation_positives
0           Affiliate License-Licensee      0.275                    18
1           Affiliate License-Licensor      0.475                     3
2                       Agreement Date      0.700                    55
3                      Anti-Assignment      0.450                    67
4                         Audit Rights      0.450                    71
5                     Cap On Liability      0.275                    57
6                    Change Of Control      0.250                    29
7    Competitive Restriction Exception      0.475                    10
8                  Covenant Not To Sue      0.250                    17
9                        Document Name      0.650                    57
10                      Effective Date      0.625                    47
11                         Exclusivity      0.575                    45
12                     Expiration Date      0.425                    57
13                       Governing Law      0.675                    51
14                           Insurance      0.525                    31
15             Ip Ownership Assignment      0.325                    28
16    Irrevocable Or Perpetual License      0.325                    23
17                  Joint Ip Ownership      0.475                     6
18                       License Grant      0.625                    80
19                  Liquidated Damages      0.475                     4
20                  Minimum Commitment      0.600                    39
21                 Most Favored Nation      0.475                     6
22             No-Solicit Of Customers      0.475                     8
23             No-Solicit Of Employees      0.475                     7
24                         Non-Compete      0.275                    14
25                   Non-Disparagement      0.475                     8
26            Non-Transferable License      0.600                    30
27  Notice Period To Terminate Renewal      0.375                    11
28                             Parties      0.550                    85
29           Post-Termination Services      0.475                    41
30                  Price Restrictions      0.475                     3
31                        Renewal Term      0.500                    20
32              Revenue/Profit Sharing      0.625                    31
33                      Rofr/Rofo/Rofn      0.475                    19
34                  Source Code Escrow      0.475                     7
35         Termination For Convenience      0.325                    27
36             Third Party Beneficiary      0.475                     4
37                  Uncapped Liability      0.275                    18
38   Unlimited/All-You-Can-Eat-License      0.475                     2
39                  Volume Restriction      0.175                    18
40                   Warranty Duration      0.150                    19

Saved calibration to: /content/cuad_fresh_training/calibration

In [33]:

import os
import json
import shutil
from google.colab import files

ROOT = "/content/cuad_fresh_training"
MODEL_PATH = f"{ROOT}/best_micro"
CALIBRATION_PATH = f"{ROOT}/calibration/thresholds.json"

EXPORT_DIR = "/content/CUAD_Classifier_v1"
ZIP_PATH = "/content/CUAD_Classifier_v1.zip"

# Verify required files
assert os.path.isdir(MODEL_PATH), "Model folder not found"
assert os.path.isfile(CALIBRATION_PATH), "Calibration file not found"

# Recreate clean export folder
if os.path.exists(EXPORT_DIR):
    shutil.rmtree(EXPORT_DIR)

os.makedirs(EXPORT_DIR)

# Copy trained model and tokenizer
shutil.copytree(
    MODEL_PATH,
    f"{EXPORT_DIR}/model"
)

# Copy calibrated thresholds
shutil.copy2(
    CALIBRATION_PATH,
    f"{EXPORT_DIR}/thresholds.json"
)

# Copy training history
history_path = f"{ROOT}/history.csv"

if os.path.exists(history_path):
    shutil.copy2(
        history_path,
        f"{EXPORT_DIR}/training_history.csv"
    )

# Create model information
with open(CALIBRATION_PATH) as f:
    calibration = json.load(f)

with open(f"{MODEL_PATH}/metadata.json") as f:
    metadata = json.load(f)

model_info = {
    "model_name": "CUAD Multi-Label Contract Classifier",
    "version": "1.0",
    "base_model": "distilbert/distilroberta-base",
    "num_categories": len(categories),
    "max_length": 512,
    "categories": list(categories),
    "validation_metrics": calibration["metrics"],
    "calibration_method": "Per-category thresholds",
    "training_checkpoint": metadata,
    "notes": (
        "Metrics are from validation data used for "
        "threshold calibration, not independent test data."
    )
}

with open(f"{EXPORT_DIR}/model_info.json", "w") as f:
    json.dump(model_info, f, indent=2)

# Zip everything
shutil.make_archive(
    "/content/CUAD_Classifier_v1",
    "zip",
    EXPORT_DIR
)

size_mb = os.path.getsize(ZIP_PATH) / (1024 ** 2)

print("MODEL EXPORTED SUCCESSFULLY")
print(f"ZIP size: {size_mb:.1f} MB")
print("Location:", ZIP_PATH)
print("Micro-F1:", calibration["metrics"]["micro_f1"])
print("Macro-F1:", calibration["metrics"]["macro_f1"])

# Download to your computer
files.download(ZIP_PATH)

MODEL EXPORTED SUCCESSFULLY
ZIP size: 292.3 MB
Location: /content/CUAD_Classifier_v1.zip
Micro-F1: 0.6308539944903582
Macro-F1: 0.39716196725830427

In [34]:

import json
import numpy as np
import torch

from torch.utils.data import DataLoader
from transformers import AutoModelForSequenceClassification
from sklearn.metrics import (
    f1_score, precision_score, recall_score
)

EXPORT_DIR = "/content/CUAD_Classifier_v1"

with open(f"{EXPORT_DIR}/thresholds.json") as f:
    thresholds = np.array(
        json.load(f)["thresholds"]
    )

with open(f"{EXPORT_DIR}/model_info.json") as f:
    info = json.load(f)

assert list(categories) == info["categories"], (
    "Category order does not match the saved model"
)

# Rebuild test data at 512 tokens
test_dataset_512 = ContractDataset(
    test_chunks["chunk_text"].fillna("").tolist(),
    y_test,
    tokenizer,
    max_length=512
)

test_loader = DataLoader(
    test_dataset_512,
    batch_size=32,
    shuffle=False
)

test_model = AutoModelForSequenceClassification.from_pretrained(
    f"{EXPORT_DIR}/model"
).to(DEVICE)

test_model.eval()

all_probs = []
all_labels = []

with torch.no_grad():
    for batch in test_loader:
        inputs = {
            k: v.to(DEVICE)
            for k, v in batch.items()
            if k != "labels"
        }

        with torch.autocast("cuda", dtype=torch.float16):
            logits = test_model(**inputs).logits

        all_probs.append(
            torch.sigmoid(logits.float()).cpu().numpy()
        )
        all_labels.append(batch["labels"].numpy())

probs = np.concatenate(all_probs)
true = np.concatenate(all_labels).astype(int)

assert probs.shape[1] == len(thresholds)

pred = (probs >= thresholds[None, :]).astype(int)

print("FINAL TEST RESULTS")
print("=" * 45)

print("Micro-F1:", f1_score(
    true, pred, average="micro", zero_division=0
))
print("Macro-F1:", f1_score(
    true, pred, average="macro", zero_division=0
))
print("Precision:", precision_score(
    true, pred, average="micro", zero_division=0
))
print("Recall:", recall_score(
    true, pred, average="micro", zero_division=0
))

per_class = f1_score(
    true, pred, average=None, zero_division=0
)

print(
    "Categories detected:",
    int((per_class > 0).sum()),
    "/",
    len(categories)
)

FINAL TEST RESULTS
=============================================
Micro-F1: 0.6187389510901591
Macro-F1: 0.3636704898777126
Precision: 0.6595477386934674
Recall: 0.5826859045504994
Categories detected: 26 / 41

In [31]:

import json
import numpy as np
import pandas as pd
import torch

from torch.utils.data import DataLoader
from transformers import AutoModelForSequenceClassification
from sklearn.metrics import (
    f1_score, precision_score, recall_score,
    average_precision_score
)

paths = {
    "best_micro": "/content/cuad_fresh_training/best_micro",
    "best_macro": "/content/cuad_fresh_training/best_macro"
}

loader = DataLoader(
    val_dataset, batch_size=32, shuffle=False
)

@torch.no_grad()
def get_predictions(path):
    m = AutoModelForSequenceClassification.from_pretrained(
        path
    ).to(DEVICE)
    m.eval()

    probs = []
    true = []

    for batch in loader:
        inputs = {
            k: v.to(DEVICE)
            for k, v in batch.items()
            if k != "labels"
        }

        with torch.autocast("cuda", dtype=torch.float16):
            logits = m(**inputs).logits

        probs.append(
            torch.sigmoid(logits.float()).cpu().numpy()
        )
        true.append(batch["labels"].numpy())

    del m
    torch.cuda.empty_cache()

    return np.concatenate(probs), np.concatenate(true).astype(int)

for name, path in paths.items():
    with open(path + "/metadata.json") as f:
        metadata = json.load(f)

    threshold = metadata["metrics"]["threshold"]

    probs, true = get_predictions(path)
    pred = (probs >= threshold).astype(int)

    rows = []

    for j, category in enumerate(categories):
        positives = int(true[:, j].sum())

        ap = (
            average_precision_score(true[:, j], probs[:, j])
            if positives > 0 else np.nan
        )

        rows.append({
            "category": category,
            "actual": positives,
            "predicted": int(pred[:, j].sum()),
            "precision": precision_score(
                true[:, j], pred[:, j], zero_division=0
            ),
            "recall": recall_score(
                true[:, j], pred[:, j], zero_division=0
            ),
            "f1": f1_score(
                true[:, j], pred[:, j], zero_division=0
            ),
            "average_precision": ap,
            "mean_positive_probability": (
                float(probs[true[:, j] == 1, j].mean())
                if positives > 0 else np.nan
            ),
            "mean_negative_probability": (
                float(probs[true[:, j] == 0, j].mean())
                if (true[:, j] == 0).any() else np.nan
            )
        })

    df = pd.DataFrame(rows).sort_values(
        ["f1", "average_precision"],
        ascending=[True, False]
    )

    print(f"\n{name.upper()} — threshold {threshold:.3f}")
    print("Micro-F1:", round(
        f1_score(true, pred, average="micro"), 4
    ))
    print("Macro-F1:", round(
        f1_score(true, pred, average="macro"), 4
    ))

    display(df)

    df.to_csv(
        f"/content/cuad_{name}_category_diagnostics.csv",
        index=False
    )

BEST_MICRO — threshold 0.475
Micro-F1: 0.5613
Macro-F1: 0.2766

,category,actual,predicted,precision,recall,f1,average_precision,mean_positive_probability,mean_negative_probability
15,Ip Ownership Assignment,28,0,0.000000,0.000000,0.000000,0.659457,0.293692,0.038500
16,Irrevocable Or Perpetual License,23,0,0.000000,0.000000,0.000000,0.643158,0.306609,0.018183
0,Affiliate License-Licensee,18,0,0.000000,0.000000,0.000000,0.513987,0.256148,0.018617
37,Uncapped Liability,18,2,0.000000,0.000000,0.000000,0.469043,0.233994,0.016777
39,Volume Restriction,18,0,0.000000,0.000000,0.000000,0.370887,0.163719,0.032632
40,Warranty Duration,19,0,0.000000,0.000000,0.000000,0.288741,0.101592,0.026200
24,Non-Compete,14,0,0.000000,0.000000,0.000000,0.268628,0.188943,0.051598
8,Covenant Not To Sue,17,0,0.000000,0.000000,0.000000,0.178771,0.132547,0.032754
6,Change Of Control,29,0,0.000000,0.000000,0.000000,0.145980,0.130803,0.035874
33,Rofr/Rofo/Rofn,19,0,0.000000,0.000000,0.000000,0.095600,0.177434,0.050199
1,Affiliate License-Licensor,3,0,0.000000,0.000000,0.000000,0.094435,0.111540,0.012645
23,No-Solicit Of Employees,7,0,0.000000,0.000000,0.000000,0.091660,0.069873,0.018115
7,Competitive Restriction Exception,10,0,0.000000,0.000000,0.000000,0.086362,0.104541,0.025236
19,Liquidated Damages,4,0,0.000000,0.000000,0.000000,0.057131,0.082867,0.025491
21,Most Favored Nation,6,0,0.000000,0.000000,0.000000,0.031959,0.033165,0.010850
22,No-Solicit Of Customers,8,0,0.000000,0.000000,0.000000,0.026485,0.028204,0.011371
34,Source Code Escrow,7,0,0.000000,0.000000,0.000000,0.017461,0.022283,0.009679
25,Non-Disparagement,8,0,0.000000,0.000000,0.000000,0.012248,0.020440,0.013972
38,Unlimited/All-You-Can-Eat-License,2,0,0.000000,0.000000,0.000000,0.009210,0.031184,0.009485
30,Price Restrictions,3,0,0.000000,0.000000,0.000000,0.007548,0.021065,0.009248
17,Joint Ip Ownership,6,0,0.000000,0.000000,0.000000,0.006829,0.027800,0.020328
36,Third Party Beneficiary,4,0,0.000000,0.000000,0.000000,0.005381,0.019475,0.012013
35,Termination For Convenience,27,1,1.000000,0.037037,0.071429,0.408675,0.303874,0.033176
29,Post-Termination Services,41,25,0.360000,0.219512,0.272727,0.223441,0.297235,0.057634
11,Exclusivity,45,57,0.280702,0.355556,0.313725,0.300930,0.373020,0.063118
20,Minimum Commitment,39,49,0.346939,0.435897,0.386364,0.313162,0.409835,0.072415
32,Revenue/Profit Sharing,31,60,0.333333,0.645161,0.439560,0.614980,0.521171,0.064263
26,Non-Transferable License,30,59,0.389831,0.766667,0.516854,0.470173,0.523222,0.033397
27,Notice Period To Terminate Renewal,11,8,0.625000,0.454545,0.526316,0.642914,0.466146,0.017165
10,Effective Date,47,76,0.460526,0.744681,0.569106,0.551788,0.595399,0.048605
4,Audit Rights,71,60,0.733333,0.619718,0.671756,0.691684,0.525819,0.060215
5,Cap On Liability,57,39,0.846154,0.578947,0.687500,0.728720,0.493019,0.038611
9,Document Name,57,82,0.585366,0.842105,0.690647,0.670316,0.750938,0.035641
2,Agreement Date,55,81,0.592593,0.872727,0.705882,0.800845,0.778826,0.035911
28,Parties,85,87,0.735632,0.752941,0.744186,0.789202,0.714277,0.034605
12,Expiration Date,57,56,0.767857,0.754386,0.761062,0.744707,0.640614,0.036078
31,Renewal Term,20,27,0.666667,0.900000,0.765957,0.794870,0.626857,0.020621
18,License Grant,80,97,0.711340,0.862500,0.779661,0.897160,0.765821,0.042951
13,Governing Law,51,72,0.666667,0.941176,0.780488,0.879030,0.803263,0.035145
3,Anti-Assignment,67,56,0.857143,0.716418,0.780488,0.803472,0.576323,0.038158
14,Insurance,31,35,0.828571,0.935484,0.878788,0.833763,0.718476,0.023461

BEST_MACRO — threshold 0.275
Micro-F1: 0.5258
Macro-F1: 0.3318

,category,actual,predicted,precision,recall,f1,average_precision,mean_positive_probability,mean_negative_probability
39,Volume Restriction,18,0,0.000000,0.000000,0.000000,0.370887,0.163719,0.032632
8,Covenant Not To Sue,17,0,0.000000,0.000000,0.000000,0.178771,0.132547,0.032754
1,Affiliate License-Licensor,3,0,0.000000,0.000000,0.000000,0.094435,0.111540,0.012645
23,No-Solicit Of Employees,7,0,0.000000,0.000000,0.000000,0.091660,0.069873,0.018115
7,Competitive Restriction Exception,10,0,0.000000,0.000000,0.000000,0.086362,0.104541,0.025236
19,Liquidated Damages,4,0,0.000000,0.000000,0.000000,0.057131,0.082867,0.025491
21,Most Favored Nation,6,0,0.000000,0.000000,0.000000,0.031959,0.033165,0.010850
22,No-Solicit Of Customers,8,0,0.000000,0.000000,0.000000,0.026485,0.028204,0.011371
34,Source Code Escrow,7,0,0.000000,0.000000,0.000000,0.017461,0.022283,0.009679
25,Non-Disparagement,8,0,0.000000,0.000000,0.000000,0.012248,0.020440,0.013972
38,Unlimited/All-You-Can-Eat-License,2,0,0.000000,0.000000,0.000000,0.009210,0.031184,0.009485
30,Price Restrictions,3,0,0.000000,0.000000,0.000000,0.007548,0.021065,0.009248
17,Joint Ip Ownership,6,0,0.000000,0.000000,0.000000,0.006829,0.027800,0.020328
36,Third Party Beneficiary,4,0,0.000000,0.000000,0.000000,0.005381,0.019475,0.012013
6,Change Of Control,29,4,0.250000,0.034483,0.060606,0.145980,0.130803,0.035874
33,Rofr/Rofo/Rofn,19,13,0.076923,0.052632,0.062500,0.095600,0.177434,0.050199
40,Warranty Duration,19,1,1.000000,0.052632,0.100000,0.288741,0.101592,0.026200
24,Non-Compete,14,5,0.600000,0.214286,0.315789,0.268628,0.188943,0.051598
32,Revenue/Profit Sharing,31,127,0.196850,0.806452,0.316456,0.614980,0.521171,0.064263
29,Post-Termination Services,41,104,0.221154,0.560976,0.317241,0.223441,0.297235,0.057634
11,Exclusivity,45,126,0.230159,0.644444,0.339181,0.300930,0.373020,0.063118
20,Minimum Commitment,39,124,0.225806,0.717949,0.343558,0.313162,0.409835,0.072415
35,Termination For Convenience,27,57,0.298246,0.629630,0.404762,0.408675,0.303874,0.033176
10,Effective Date,47,115,0.313043,0.765957,0.444444,0.551788,0.595399,0.048605
26,Non-Transferable License,30,82,0.304878,0.833333,0.446429,0.470173,0.523222,0.033397
37,Uncapped Liability,18,15,0.600000,0.500000,0.545455,0.469043,0.233994,0.016777
31,Renewal Term,20,49,0.387755,0.950000,0.550725,0.794870,0.626857,0.020621
27,Notice Period To Terminate Renewal,11,28,0.392857,1.000000,0.564103,0.642914,0.466146,0.017165
16,Irrevocable Or Perpetual License,23,39,0.461538,0.782609,0.580645,0.643158,0.306609,0.018183
13,Governing Law,51,103,0.475728,0.960784,0.636364,0.879030,0.803263,0.035145
4,Audit Rights,71,91,0.571429,0.732394,0.641975,0.691684,0.525819,0.060215
15,Ip Ownership Assignment,28,34,0.588235,0.714286,0.645161,0.659457,0.293692,0.038500
0,Affiliate License-Licensee,18,16,0.687500,0.611111,0.647059,0.513987,0.256148,0.018617
9,Document Name,57,89,0.539326,0.842105,0.657534,0.670316,0.750938,0.035641
3,Anti-Assignment,67,98,0.561224,0.820896,0.666667,0.803472,0.576323,0.038158
2,Agreement Date,55,89,0.539326,0.872727,0.666667,0.800845,0.778826,0.035911
18,License Grant,80,131,0.557252,0.912500,0.691943,0.897160,0.765821,0.042951
28,Parties,85,103,0.640777,0.776471,0.702128,0.789202,0.714277,0.034605
5,Cap On Liability,57,59,0.694915,0.719298,0.706897,0.728720,0.493019,0.038611
12,Expiration Date,57,76,0.631579,0.842105,0.721805,0.744707,0.640614,0.036078
14,Insurance,31,39,0.743590,0.935484,0.828571,0.833763,0.718476,0.023461

In [25]:

import json
import numpy as np
import pandas as pd
import torch

from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer
)
from sklearn.metrics import (
    precision_recall_fscore_support
)

BEST_PATH = "/content/cuad_best_model"

model = AutoModelForSequenceClassification.from_pretrained(
    BEST_PATH
).to(DEVICE)

tokenizer = AutoTokenizer.from_pretrained(BEST_PATH)

with open(f"{BEST_PATH}/training_config.json") as f:
    saved_config = json.load(f)

threshold = saved_config["best_threshold"]

probs, true = get_validation_outputs(
    model, validation_loader
)

print("BEST MODEL RESULTS")

for t in [0.5, threshold]:
    metrics = calculate_metrics(probs, true, t)
    print(f"\nThreshold: {t:.3f}")
    print(metrics)

predictions = (probs >= threshold).astype(int)

p, r, f1, support = precision_recall_fscore_support(
    true,
    predictions,
    average=None,
    zero_division=0
)

per_category = pd.DataFrame({
    "category": categories,
    "precision": p,
    "recall": r,
    "f1": f1,
    "actual_count": support,
    "predicted_count": predictions.sum(axis=0)
})

print("\nBEST PERFORMING CATEGORIES")
display(
    per_category.sort_values(
        "f1", ascending=False
    ).head(15)
)

print("\nWORST PERFORMING CATEGORIES")
display(
    per_category.sort_values(
        "f1", ascending=True
    ).head(15)
)

per_category.to_csv(
    "/content/cuad_transformer_category_metrics.csv",
    index=False
)

BEST MODEL RESULTS

Threshold: 0.500
{'micro_f1': 0.25357873210633947, 'macro_f1': 0.06659059514781399, 'precision': 0.6326530612244898, 'recall': 0.1585677749360614, 'predicted_positives': 294}

Threshold: 0.260
{'micro_f1': 0.2754237288135593, 'macro_f1': 0.08904916259368956, 'precision': 0.36363636363636365, 'recall': 0.2216538789428815, 'predicted_positives': 715}

BEST PERFORMING CATEGORIES

,category,precision,recall,f1,actual_count,predicted_count
28,Parties,0.747126,0.764706,0.755814,85,87
2,Agreement Date,0.580247,0.854545,0.691176,55,81
9,Document Name,0.560976,0.807018,0.661871,57,82
10,Effective Date,0.419753,0.723404,0.531250,47,81
12,Expiration Date,0.306122,0.263158,0.283019,57,49
13,Governing Law,0.176871,0.509804,0.262626,51,147
29,Post-Termination Services,0.140351,0.195122,0.163265,41,57
3,Anti-Assignment,0.180000,0.134328,0.153846,67,50
5,Cap On Liability,0.128205,0.175439,0.148148,57,78
8,Covenant Not To Sue,0.000000,0.000000,0.000000,17,0
7,Competitive Restriction Exception,0.000000,0.000000,0.000000,10,0
6,Change Of Control,0.000000,0.000000,0.000000,29,0
4,Audit Rights,0.000000,0.000000,0.000000,71,3
1,Affiliate License-Licensor,0.000000,0.000000,0.000000,3,0
0,Affiliate License-Licensee,0.000000,0.000000,0.000000,18,0

WORST PERFORMING CATEGORIES

,category,precision,recall,f1,actual_count,predicted_count
0,Affiliate License-Licensee,0.0,0.0,0.0,18,0
1,Affiliate License-Licensor,0.0,0.0,0.0,3,0
6,Change Of Control,0.0,0.0,0.0,29,0
4,Audit Rights,0.0,0.0,0.0,71,3
7,Competitive Restriction Exception,0.0,0.0,0.0,10,0
14,Insurance,0.0,0.0,0.0,31,0
11,Exclusivity,0.0,0.0,0.0,45,0
8,Covenant Not To Sue,0.0,0.0,0.0,17,0
15,Ip Ownership Assignment,0.0,0.0,0.0,28,0
22,No-Solicit Of Customers,0.0,0.0,0.0,8,0
21,Most Favored Nation,0.0,0.0,0.0,6,0
20,Minimum Commitment,0.0,0.0,0.0,39,0
19,Liquidated Damages,0.0,0.0,0.0,4,0
18,License Grant,0.0,0.0,0.0,80,0
17,Joint Ip Ownership,0.0,0.0,0.0,6,0

In [26]:

import numpy as np
import pandas as pd
from sklearn.metrics import f1_score, precision_score, recall_score

# Assumes 'probs' and 'true' are from the full validation set
assert probs.shape == true.shape
assert probs.shape[1] == len(categories)

global_threshold = 0.26
thresholds = np.full(len(categories), global_threshold)

# Only tune categories with enough validation positives.
# Otherwise retain the global threshold to reduce overfitting.
for j in range(len(categories)):
    if true[:, j].sum() < 10:
        continue

    best_f1 = -1
    best_t = global_threshold

    for t in np.arange(0.05, 0.81, 0.025):
        pred = (probs[:, j] >= t).astype(int)

        score = f1_score(
            true[:, j],
            pred,
            zero_division=0
        )

        if score > best_f1:
            best_f1 = score
            best_t = float(t)

    thresholds[j] = best_t

pred_global = (probs >= global_threshold).astype(int)
pred_tuned = (probs >= thresholds[None, :]).astype(int)

for name, pred in [
    ("Global threshold", pred_global),
    ("Per-category thresholds", pred_tuned)
]:
    print("\n", name)
    print("Micro-F1:", round(
        f1_score(true, pred, average="micro", zero_division=0), 4
    ))
    print("Macro-F1:", round(
        f1_score(true, pred, average="macro", zero_division=0), 4
    ))
    print("Precision:", round(
        precision_score(true, pred, average="micro", zero_division=0), 4
    ))
    print("Recall:", round(
        recall_score(true, pred, average="micro", zero_division=0), 4
    ))
    print("Predicted positives:", int(pred.sum()))

threshold_df = pd.DataFrame({
    "category": categories,
    "threshold": thresholds,
    "validation_positives": true.sum(axis=0)
})

display(threshold_df)

threshold_df.to_csv(
    "/content/cuad_category_thresholds.csv",
    index=False
)

 Global threshold
Micro-F1: 0.2754
Macro-F1: 0.089
Precision: 0.3636
Recall: 0.2217
Predicted positives: 715

 Per-category thresholds
Micro-F1: 0.1174
Macro-F1: 0.1403
Precision: 0.0666
Recall: 0.497
Predicted positives: 8759

                              category  threshold  validation_positives
0           Affiliate License-Licensee      0.050                    18
1           Affiliate License-Licensor      0.260                     3
2                       Agreement Date      0.725                    55
3                      Anti-Assignment      0.175                    67
4                         Audit Rights      0.075                    71
5                     Cap On Liability      0.250                    57
6                    Change Of Control      0.100                    29
7    Competitive Restriction Exception      0.050                    10
8                  Covenant Not To Sue      0.050                    17
9                        Document Name      0.475                    57
10                      Effective Date      0.625                    47
11                         Exclusivity      0.075                    45
12                     Expiration Date      0.200                    57
13                       Governing Law      0.250                    51
14                           Insurance      0.100                    31
15             Ip Ownership Assignment      0.050                    28
16    Irrevocable Or Perpetual License      0.050                    23
17                  Joint Ip Ownership      0.260                     6
18                       License Grant      0.125                    80
19                  Liquidated Damages      0.260                     4
20                  Minimum Commitment      0.075                    39
21                 Most Favored Nation      0.260                     6
22             No-Solicit Of Customers      0.260                     8
23             No-Solicit Of Employees      0.260                     7
24                         Non-Compete      0.075                    14
25                   Non-Disparagement      0.260                     8
26            Non-Transferable License      0.050                    30
27  Notice Period To Terminate Renewal      0.125                    11
28                             Parties      0.500                    85
29           Post-Termination Services      0.200                    41
30                  Price Restrictions      0.260                     3
31                        Renewal Term      0.150                    20
32              Revenue/Profit Sharing      0.050                    31
33                      Rofr/Rofo/Rofn      0.150                    19
34                  Source Code Escrow      0.260                     7
35         Termination For Convenience      0.150                    27
36             Third Party Beneficiary      0.260                     4
37                  Uncapped Liability      0.050                    18
38   Unlimited/All-You-Can-Eat-License      0.260                     2
39                  Volume Restriction      0.150                    18
40                   Warranty Duration      0.050                    19

Test predictions

In [10]:

sample_contract = """
This agreement may be terminated by either party
upon thirty days written notice.
"""

result = predict_clauses(
    sample_contract,
    model,
    tokenizer
)

print("Number of outputs:", len(result["probabilities"]))

print("\nPredicted label indices:")
print(np.where(result["predictions"] == 1)[0])

print("\nFirst 10 probabilities:")
print(result["probabilities"][:10])

Number of outputs: 41

Predicted label indices:
[ 0  3  4  7  8 10 14 16 17 19 21 22 25 27 28 32 38 39 40]

First 10 probabilities:
[0.51199037 0.44088367 0.48987353 0.5009758  0.54422444 0.4848301
 0.4908441  0.53987724 0.55657274 0.47886267]

Save the model

In [11]:

SAVE_PATH = "./cuad_distilroberta"

model.save_pretrained(SAVE_PATH)
tokenizer.save_pretrained(SAVE_PATH)

print("Model saved successfully!")

Model saved successfully!